# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Homepage of Yuejiang Yu
description: >- # this means to ignore newlines until "baseurl:"
  Undergraduate Student at Peking University
# baseurl: "/bay" # the subpath of the site
url: "https://pkuyyj.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yuyuejiang@pku.edu.cn
      link: mailto:yuyuejiang@pku.edu.cn
    - name: WeChat
      value: pkucs19yyj_1220
  follow:
#     - name: Twitter
#       link: http://twitter.com/YourTwitterUsername
#       username: "@YourTwitterUsername"
#     - name: Facebook
#       link: http://facebook.com/YourFacebookUsername
#     - name: LinkedIn
#       link: http://linkedin.com/in/YourLinkedInUsername
     - name: GitHub
       link: http://github.com/pkuyyj
#     - name: Dribbble
#       link: https://dribbble.com/YourDribbbleUsername
#     - name: RSS
#       link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
theme: bay_jekyll_theme

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
