# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Changyeon Lee
description: >- # this means to ignore newlines until "baseurl:"
  Changyeon Lee's Github Blog.
baseurl: "" # the subpath of the site
url: "https://changyeon2.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpeg

#header:
  #pages:
   # - name: Home
   #   slug: /
   # - name: Work
   # - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: cyeon219@yonsei.ac.kr
      link: mailto:cyeon219@yonsei.ac.kr
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/changyeon2
    - name: GitHub
      link: http://github.com/changyeon2

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
