# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sungbin Park
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/spark" # the subpath of the site
url: "https://sungbinp.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Webpage

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: spark224@gmu.edu
      link: mailto:spark224@gmu.edu
   # - name: WeChat
   #   value: YourWeChatUsername
   #   link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/sungbin_park_
      username: "@sungbin_park_"
   # - name: Facebook
   #   link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/spark01/
    - name: Google Scholar
      link: https://scholar.google.com/citations?user=rd0BrEwAAAAJ&hl=ko&authuser=3
   # - name: Dribbble
   #   link: https://dribbble.com/YourDribbbleUsername
   # - name: RSS
   #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
