# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Personal site
description: >- # this means to ignore newlines until "baseurl:"
  This is a simple personal site.
baseurl: "/nhuynghu.github.io" # the subpath of the site
url: "https://nhuynghu.github.io" # the base hostname & protocol for the site
og_image: /assets/img/nhuy_sg.png
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Work


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: nhuynghu.tgvn@gmail.com
      link: mailto:nhuynghu.tgvn@gmail.com

  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/nhuy-nguyen-0107ny0107/
    - name: GitHub
      link: http://github.com/nhuynghu


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
